### ISSUE TITLE
Proposal to delete this repo

### ISSUE THREAD

**Issue by Asimov4** [CommunityDataScienceCollective/CDSW_Babynames#2]
I would suggest deleting this repo in favor of the official https://github.com/CommunityDataScienceCollective/babynames-cdsw for consistency.

I went ahead and sent a pull request with the proposed changes that were introduced here in the following pull request: https://github.com/CommunityDataScienceCollective/babynames-cdsw/pull/1

**Comment by makoshark** [comment]
@Asimov4 Thanks! I'll close this and delete it now.
